# Generated by Django 4.2.3 on 2023-07-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_expense_quantity_alter_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderId',
            field=models.IntegerField(default=0),
        ),
    ]
